import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const packageJsonPath = path.join(__dirname, '..', 'package.json')
const versionFilePath = path.join(__dirname, '..', 'src', 'renderer', 'version.ts')

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'))
const version = packageJson.version

const versionContent = `// This file is automatically generated during the build process
// Do not edit manually
export const APP_VERSION = "${version}"
`

fs.writeFileSync(versionFilePath, versionContent)
console.log(`✓ Generated src/renderer/version.ts with version ${version}`)
